"""
PDF security audit summary generation.

Uses reportlab's Platypus layer (structured flowables: Paragraph, Table,
Spacer) rather than the low-level Canvas API - Platypus handles page
breaks and flow automatically when content overflows a page, which
matters here since the number of scans/alerts/incidents varies per user.

Deliberately using only plain ASCII/Latin text throughout - reportlab's
built-in fonts render Unicode subscript/superscript characters as solid
black boxes, a known gotcha worth avoiding entirely.
"""

import io
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

_STYLES = getSampleStyleSheet()
_TITLE_STYLE = ParagraphStyle(
    "ReportTitle", parent=_STYLES["Title"], fontSize=20, spaceAfter=4, textColor=colors.HexColor("#1B2230")
)
_SUBTITLE_STYLE = ParagraphStyle(
    "ReportSubtitle", parent=_STYLES["Normal"], fontSize=10, textColor=colors.HexColor("#666666")
)
_SECTION_STYLE = ParagraphStyle(
    "SectionHeading", parent=_STYLES["Heading2"], spaceBefore=18, spaceAfter=8, textColor=colors.HexColor("#1B2230")
)

_TABLE_HEADER_BG = colors.HexColor("#1B2230")
_TABLE_HEADER_FG = colors.white
_TABLE_GRID = colors.HexColor("#CCCCCC")


def _table(headers: list[str], rows: list[list[str]]) -> Table:
    data = [headers] + rows if rows else [headers, ["No data available"] + [""] * (len(headers) - 1)]
    table = Table(data, hAlign="LEFT", repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _TABLE_HEADER_BG),
                ("TEXTCOLOR", (0, 0), (-1, 0), _TABLE_HEADER_FG),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, _TABLE_GRID),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F5F5")]),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def generate_security_report_pdf(summary: dict, user_email: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    elements = []

    elements.append(Paragraph("CyberGuard AI - Security Audit Summary", _TITLE_STYLE))
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    elements.append(Paragraph(f"Generated for: {user_email} | {generated_at}", _SUBTITLE_STYLE))
    elements.append(Spacer(1, 16))

    elements.append(Paragraph("Executive Summary", _SECTION_STYLE))
    score_display = (
        f"{summary['average_security_score']}/100" if summary["average_security_score"] is not None else "N/A"
    )
    summary_rows = [
        ["Average Security Score", score_display],
        ["Total Website Scans", str(summary["total_scans"])],
        ["Total Security Alerts", str(summary["total_alerts"])],
        ["Unresolved Alerts", str(summary["unresolved_alerts"])],
        ["Total Incidents", str(summary["total_incidents"])],
        ["Open/Investigating Incidents", str(summary["open_incidents"])],
    ]
    elements.append(_table(["Metric", "Value"], summary_rows))

    elements.append(Paragraph("Recent Website Scans", _SECTION_STYLE))
    scan_rows = [
        [s["target_url"][:40], s["status"], str(s["security_score"] or "-"), s["started_at"][:10]]
        for s in summary["recent_scans"]
    ]
    elements.append(_table(["Target", "Status", "Score", "Date"], scan_rows))

    elements.append(Paragraph("Recent Security Alerts", _SECTION_STYLE))
    alert_rows = [
        [a["title"][:45], a["severity"], a["source_ip"], a["created_at"][:10]]
        for a in summary["recent_alerts"]
    ]
    elements.append(_table(["Alert", "Severity", "Source IP", "Date"], alert_rows))

    elements.append(Paragraph("Recent Incidents", _SECTION_STYLE))
    incident_rows = [
        [i["title"][:45], i["status"], i["severity"], i["created_at"][:10]]
        for i in summary["recent_incidents"]
    ]
    elements.append(_table(["Title", "Status", "Severity", "Date"], incident_rows))

    elements.append(Spacer(1, 20))
    elements.append(
        Paragraph(
            "This report was automatically generated by CyberGuard AI. Data reflects the "
            "state of the platform at the time of generation.",
            _SUBTITLE_STYLE,
        )
    )

    doc.build(elements)
    return buffer.getvalue()
